### ISSUE TITLE
pbf output is not supported on mac

### ISSUE THREAD

**Issue by warrenwyf** [roelderickx/ogr2osm#20]
Installed ogr2osm via pip.

When running command `ogr2osm -o xxx.osm.pbf xxx`, an warning is reported: `WARNING: PBF output is not supported on this system but the outputfile has extension .pbf, automatically removing .pbf extension`.

**Comment by warrenwyf** [comment]
The reason has been found, protobuf is not automatically installed in the dependency, you need to install it manually:

`pip install protobuf`

**Comment by roelderickx** [comment]
Thanks for your report and good to read your problem was resolved. Since most people don't need PBF output the dependency on protobuf is optional and can be found in `optional-requirements.txt`.
I'll include a better hint in the warning message, it will save the next user with the same issue 2 hours of headache.
