### ISSUE TITLE
Adding Conversion directly to PBF or OSM.pbf 

### ISSUE THREAD

**Issue by kabilsharma** [roelderickx/ogr2osm#52]
Does this tool support converting geojson to PBF or OSM.pbf  directly .

**Comment by roelderickx** [comment]
Yes it does, essentially
```
ogr2osm --pbf -o output.pbf input.geojson
```
should do the trick.

**Comment by kabilsharma** [comment]
Works with pbf not with osm.pbf.  Thanks

**Comment by roelderickx** [comment]
Isn't that just a matter of passing the right parameters? For example
```
ogr2osm --pbf -o output.osm.pbf input.geojson
```

**Comment by kabilsharma** [comment]
osm.pbf is a completely different format.

**Comment by roelderickx** [comment]
In that case we have to develop a new data writer, which can easily be defined as a subclass of DataWriterBase.
However I can't seem to find specific documentation of the osm.pbf file format. Can you point me in the right direction?

**Comment by kabilsharma** [comment]
https://github.com/openstreetmap/OSM-binary

Here is the relevant info.

The geojson  if is 1 Gb
OSM will be 1.2 Gb
Pbf will be 800 mb
osm.pbf will be 100 mb

**Comment by roelderickx** [comment]
> https://github.com/openstreetmap/OSM-binary

This is the reference implementation for the PBF file format. Its README file points to the [OpenStreetMap wiki page describing the PBF format](https://wiki.openstreetmap.org/wiki/PBF_Format), on which the ogr2osm PBF implementation is based.

> Here is the relevant info.
>
> The geojson if is 1 Gb
> OSM will be 1.2 Gb
> Pbf will be 800 mb
> osm.pbf will be 100 mb

The size difference between both pbf files is probably due to a different data compression algorithm, although it is hard to believe the difference will be that significant. Maybe some optional data is omitted too? How did you create the pbf file? And the osm.pbf file?

**Comment by kabilsharma** [comment]
[image: {007D204C-5E01-42D4-92FC-181B7D9ACE84}.png]

Yes, you seem to be right.

[image: {25C4EAA8-F302-48A7-9AC3-C16C50479E9E}.png]
